config/routes.rb
Dockrealty::Application.routes.draw do
  
  match '/contact', :to => 'pages#contact'
  match '/terms',  :to => 'pages#terms'
  match '/privacy', :to => 'pages#privacy'
  match '/history', :to => 'pages#history'
  match '/advertising', :to => 'pages#advertising'
  
  root :to => 'pages#home'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def terms
    @title = "Terms of Use"
  end
  
  def privacy
    @title = "Privacy Policy"
  end
  
  def history
    @title = "History"
  end
  
  def advertising
    @title = "Advertising"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Dock Realty"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  # 
  # def email
  #   base_email = "@dockrealty.com"
  #     if @email.nil?
  #       "info + #{base_email}""
  #     else
  #      "#{base_title} | #{@title}"
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<nav>
 <ul>
   <li><%= link_to "Terms", terms_path %></li>
   <li><%= link_to "Privacy Policy", privacy_path %></li>
   <li><%= link_to "Contact", contact_path %></li>
   <li><%= link_to "History", history_path %></li>
	</ul>
</nav>
<%= link_to image_tag("dr_logo_small.jpg", :alt => "Dock Realty"), root_path %>
<p>Copyright 2003 - 2011, Dock Realty, Inc.. All rights reserved.<br>
Any and all information on this site may not be duplicated or copied 
without the expressed written permission of Dock Realty, Inc.</p>

app/views/layouts/_header.html.erb
<h1>Listing New and Used Boat Docks, Slips and Lifts</h1>
<h2>(573)-374-8849 / (866)-DOC-RLTY</h2>
<a href="mailto:sales@dockrealty.com">sales@dockrealty.com</a>

app/views/layouts/_mainNav.html.erb
<ul>
	<li><%= link_to "Home", root_path %></li>
	<li><h2>Listings</h2>
    <ul>
      <li><h3>Docks</h3>
        <ul>
					<li><%= link_to "1 Well Docks", '#' %></li>
					<li><%= link_to "2 Well Docks", '#' %></li>
					<li><%= link_to "3+ Well Docks", '#' %></li>
					<li><%= link_to "Commercial", '#' %></li>
        </ul>
      </li>
    </ul>
		<ul>
			<li><h3>Lifts</h3>
	      <ul>
					<li><%= link_to "Boat Lifts", '#' %></li>
					<li><%= link_to "New Boat Lifts", '#' %></li>
					<li><%= link_to "PWC Jet Ski Lifts", '#' %></li>
					<li><%= link_to "All Lifts", '#' %></li>
	      </ul>
	    </li>
	  </ul>
		<ul>
		<li><h3>Slips</h3>
      <ul>
				<li><%= link_to "All Slips", '#' %></li>
				<li><%= link_to "For Sale", '#' %></li>
				<li><%= link_to "For Lease", '#' %></li>
      </ul>
    </li>
	</ul>
  </li>
</ul>

<ul>
  <li><h2>Accessories</h2>
    <ul>
			<li><h3>Example</h3>
        <ul>
          <li><a href="index.html#">Popout!</a><!-- link to seo vertical tut -->		
            <ul>
              <li><a href="vs1.html" title="Vertical Menu - Page 1">Stage 1</a></li>
              <li><a href="vs2.html" title="Vertical Menu - Page 2">Stage 2</a></li>			
              <li><a href="vs3.html" title="Vertical Menu - Page 3">Stage 3</a></li>
              <li><a href="vs4.html" title="Vertical Menu - Page 4">Stage 4</a></li>
              <li><a href="vs5.html" title="Vertical Menu - Page 5">Stage 5</a></li>			
              <li><a href="vs6.html" title="Vertical Menu - Page 6">Stage 6</a></li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </li>
</ul>

<ul>
  <li><h2>Company Info</h2>
    <ul>
			<li><h3>About Us</h3>
				<ul>
					<li><%= link_to "Contact Us", contact_path %></li>
					<li><%= link_to "History", history_path %></li>
					<li><%= link_to "Advertising", advertising_path %></li>
				</ul>	
			</li>
			<li><h3>Legal</h3>
				<ul>
					<li><%= link_to "Terms", terms_path %></li>
					<li><%= link_to "Privacy Policy", privacy_path %></li>
        </ul>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!-- [if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif] -->
<%= stylesheet_link_tag 'reset', :media => 'screen' %>
<%= stylesheet_link_tag 'global', :media => 'screen' %>

app/views/layouts/_userPanel.html.erb
<ul class="sf.menu">
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "Help", '#' %></li>
	<li><%= link_to "Sign in", '#' %></li>
</ul>
<h1>DockRealty.com</h1>
<h2>Listing New & Used Boat Docks Slips & Lifts</h2>
<h3>If you wish to list your dock please contact us: 
	<a href="mailto:sales@dockrealty.com">sales@dockrealty.com</a></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
		<div id="header">
		<%= render 'layouts/header' %>
		</div>
			<div id="colmask">
				<div id="colmid">
					<div id="colright">
						<div id="col1wrap">
							<div id="col1pad">
								<div id="content">
								<%= yield %>
								</div>
							</div>
						</div>
						<div id="mainNav">
						<%= render 'layouts/mainNav' %>
						</div>
						<div id="userPanel">
						<%= render 'layouts/userPanel' %>
						</div>
					</div>
				</div>
			</div>
			<div id="footer">
      <%= render 'layouts/footer' %>
    	</div>
  </body>
</html>

app/views/pages/advertising.html.erb
<h1>Our Advertising</h1>
<p>Dock Realty, Inc.&nbsp; maximizes the visibility of your Boat Dock or Lift by advertising in the following media:</p>
<blockquote> <p class="center">
Radio * Billboards * Television * Classifieds * Boat Shows * Boating Magazines * Real Estate Guides * Hot Sheets to Marinas * Hot Sheets to Realtors * Web Search Engines</p></blockquote>
<p><img border="0" src="../images/mag_ads.jpg"></p>
<h3>Look for our <strong>Billboards</strong> and Ads around your lake:</h3>
<p><img border="0" src="../images/dockrealty_med.jpg"></p>
<h3>Trade Shows:</h3>
<h3><img border="0" src="../images/trade_show_stl.jpg"></h3>
<h3>Other Marketing:</h3>
<p>For all other advertising or marketing issues, please <a href="mailto:sales@dockrealty.com"> leave
a message for us</a>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>To send us an e-mail message, please complete the following information. Make sure your “Subject” line contains a <strong>complete</strong> description of your comment to help us route you to the proper department. Remember your question or comment is important to us and we will get back to you as soon as possible.</p>
<%= image_tag("dr_office.jpg", :alt => "Dock Realty", :class => "floatright") %>

<p>
Dock Realty Inc.<br/>
PO Box 8<br/>
2820 Bagnell Dam Blvd, Suite 5A<br>
Lake Ozark, MO 65049-0008</p>

<p>
Phone: (573) 374-8849<br>
Toll Free: (866) DOC-RLTY / (866) 362-7589<br>
Fax: <F(573) 374 9285\<br>
Toll Free: (866) DOCK-FAX / (866) 362-5329<br>
<a href="mailto:info@dockrealty.com">info@dockrealty.com</a></p>

app/views/pages/history.html.erb
<h1>Dock Realty - Company History</h1>

<%= image_tag("dhotz.jpg", :alt => "Dave Hotz", :size  => "155x200", :class => "floatright" ) %>

<p>Dock Realty was formed in January 2003 as a result of a vision I had to access the entire inventory of previously owned boat docks, slips and lifts available in a selected area.   Home buyers could search the MLS listings or Realtor.com to see available real-estate listings, but no such tools were available in the dock world. Used dock buyers were left having to scan classified ads in papers or making calls to dock companies to check their used inventory which could change daily.  Sellers had no way to cost effectively present their item to sell.   Ads in newspapers where costly and could not show the quality of the item for sale.  Our resultant Dock Realty web site now serves as central place for dock sellers and buyers to come together.</p>

<p>Dock Realty is much more than a listing service, think of us as a concierge service for dock buyers and sellers.  Dock Realty will help in every aspect of the selling and buying process, from photographing the dock to issuing the bill of sale.</p>

<p>Dock Realty is in its seventh year in business and have proudly assisted over 7000 clients over the last eight years. We thank all of you for contributing to our success.</p>

<p>The vision, one URL to access the current inventory of pre-owned boat docks, slips and lifts. The solution, www.dockrealty.com.</p>

<p>Sincerely,<br>
	 Dave Hotz</p>

app/views/pages/home.html.erb
<%= image_tag("dockrealtymap.jpg", :alt => "Dock Realty", :size  => "571x450") %>

app/views/pages/privacy.html.erb
<h1>Dock Realty Privacy Policy</h1>

<h2>Terms and Conditions of Use</h2>
<p>Dock Realty, Inc. is committed to protecting the privacy of our customers. The following statement discloses our information gathering and dissemination practices for the dockrealty.com Web site.</p>

<h2>How is my information used?</h2>
<p>Our primary goal in collecting personal information is to provide you with a customized experience. Dockrealty.com uses information collected from server log files, such as IP addresses, to help diagnose problems with our services, to administer our Web site, and to report and gather aggregate information about site usage and user demographics. Dockrealty.com also uses code included on every page on our site to track the traffic on pages and compile information about users, such as paths through the site, browsers used, time spent on site, frequency of return visits, etc. This system does not garner any person information about our readers, such as names. Dockrealty.com may share aggregated data with advertisers or business partners.</p>
<p>Dockrealty.com also uses cookies to store and sometimes track information about you. A cookie is a small amount of data that is sent to your browser from a Web service and stored on your computer's hard drive. Dockrealty.com uses cookies to deliver targeted advertising based on your behavior or demographics and to track your number of entries in some of our promotions and contests.</p>
	
<h2>With whom is my information shared?</h2>
<p>Aggregate information compiled by dockrealty.com  may be shared with advertisers and business partners as well as used by Dock Realty, Inc..</p>

<h2>Linked Sites</h2>
<p>Please be aware that dockrealty.com's promotional partners, advertisers, sponsors, third-party Internet sites, and content providers accessible through dockrealty.com may have their own privacy and data collection policies and practices. Dockrealty.com is not responsible for any actions or policies of such third parties. Users should check the applicable privacy policies of those third parties when providing personally identifiable information through co-sponsored, affiliated or linked sites.</p>

<h2>Policy Changes and Questions</h2>
<p>Dockrealty.com reserves the right to change this policy at any time. Please check this page periodically for changes. (The most recent change was made on January 19th, 2003)</p>

<%= link_to "For a link to our terms of use please click here", terms_path %>

<p>Our Address and Contact Information:</p>

<span class="Address">Dock Realty, Inc.
PO Box 8<br>
Lake Ozark, MO 65049<br>
(866) DOC-RLTY</span>

app/views/pages/terms.html.erb
<h1>Terms of Use Dock Realty Brokerage Services</h1>
<p>Welcome to dockrealty.com, an interactive online dock and lift
listing  service operated by the Dock Realty Corporation. By using this site, you signify your agreement to all terms, conditions, and notices contained or referenced herein ("Terms and Conditions of Use"). If you do not agree to these Terms and Conditions of Use, please do not use this site.
Dock Realty, Inc.&nbsp; reserves the right, in its sole discretion, to modify, alter or otherwise update these Terms and Conditions of Use at any time. By using this site after notice of such changes is posted, you agree to be bound by the modifications, alterations or updates.</p>
<h2>Linked Sites</h2>
<p>This site may contain links to other sites on the Internet ("Linked Sites").  Dock Realty, Inc. is not responsible for the content, advertising, products or other materials made available on or through any Linked Site. The links to these sites are for your convenience only, and you access them at your own risk.  Dock Realty, Inc.&nbsp; shall not be held responsible or liable, directly or indirectly, for any loss or damage caused or alleged to have been caused to a user in connection with such Linked Sites.</p>
Dock Realty, Inc. welcomes links to this site. You may establish a link to this site, provided that the link does not state or imply any sponsorship or endorsement of your site by Dock Realty, Inc..&nbsp; You may not use on your site any logos, trademarks, service marks, or copyrighted materials appearing on this site, including but not limited to any logos or characters, without the express written consent of the owner of the mark or right. You may not frame or otherwise incorporate into another site the content or other materials on this site without prior written consent.&nbsp;</p>
<h2>Copyright and Trademarks</h2>
<p>Dockrealty.com contains copyrighted material, trademarks and other proprietary information including, text, software, photos, video, graphics, music and sound. All content included on this site, such as text, software, photos, video, graphics, music, sound, and logos, is protected by copyrights, trademarks, and other rights, which are owned and/or controlled by
Dock Realty, Inc. or by other parties. Dock Realty, Inc.&nbsp; owns a copyright in the selection, coordination arrangement and enhancement of such content, as well as the content original to it. Each third-party content provider owns the copyright in content original to it. You may use material from this site only for your own personal, non-commercial use. This site or any portion of this site may not be modified, published, reproduced, duplicated, copied, uploaded, downloaded, posted, transmitted, sold, or otherwise exploited for any commercial purpose that is not expressly permitted by Dock Realty, Inc. or expressly permitted under copyright law. In the event of any permitted copying, redistribution, or publication of copyrighted material, no changes in or deletion of author attribution, trademark legend or copyright notice shall be made. You acknowledge that you do not acquire any ownership rights by downloading copyrighted material.</p>
<h2>Disclaimer</h2>
<p class="disclaimer"> this site is provided by dock realty, inc. on an "as is" basis. dock realty, inc. makes no representations or warranties of any kind, express or implied, as to the operation of the site or the information, content, materials, or products listed on this site. to the full extent permissible by applicable law, dock realty, inc. disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose.&nbsp; dock realty, inc.. will not be liable for any damages of any kind arising from the use of, or inability to use, this site, including, but not limited to direct, indirect, incidental, punitive, and consequential damages.</p>
<h2>Identification</h2>
<p>You agree to indemnify Dock Realty, Inc. and its officers, directors, employees, agents, distributors, and affiliates from and against any and all third party claims, demands, liabilities, costs, or expenses, including reasonable attorney’s fees, that arise from your use or misuse of this site.</p>

<%= link_to "For our privacy policy, please click here", privacy_path %>

<p>Our Address and Contact Information: <br>

<span class="address">Dock Realty, Inc.<br>
PO Box 8<br>
Lake Ozark, MO 65049<br>
(866) DOC-RLTY</p></span>